Add some German Translation
BillyGalbreath/Pl3xMap pull request #118
Opened 2022-07-25 17:44 UTC by rotvproHD

Just add some German Translation and also format the messages in that a bit nicer,
Im gonna make a commit for some english translation Formatting ;)

2022-07-25 18:11 UTC, BillyGalbreath requested changes
Your language file doesn't seem to be complete. I still a lot of English in it, and the changes you made in the Lang java class don't seem to match your language file

2022-07-25 18:11 UTC, BillyGalbreath commented on plugin/src/main/java/net/pl3x/map/configuration/Lang.java
> +    public static String COMMAND_CANCELRENDER_SUCCESS = "<green>Render on <grey><world> <green>has been cancelled";
close grey instead of opening a new green

2022-07-25 18:11 UTC, BillyGalbreath commented on plugin/src/main/java/net/pl3x/map/configuration/Lang.java
> +    public static String COMMAND_HIDE_ALREADY_HIDDEN = "<grey>><player> <red>is already hidden from map";
extra `>`

2022-07-25 18:17 UTC, rotvproHD commented
> Your language file doesn't seem to be complete. I still a lot of English in it, and the changes you made in the Lang java class don't seem to match your language file

Yeah, I just wanted to edit some basic texts first, the rest I’ll do tomorrow ;)

2022-07-26 10:34 UTC, rotvproHD commented
Ok, everything should be done now

2022-07-27 08:22 UTC, rotvproHD commented
merge when

2022-07-27 09:34 UTC, BillyGalbreath commented
The changes you made in the Lang java class still don't seem to match your language file. And your language file seems to be missing some placeholders.

2022-08-02 09:21 UTC, rotvproHD commented
(┛ಠ_ಠ)┛彡┻━┻

2022-08-12 13:42 UTC, BillyGalbreath approved these changes

2022-08-12 13:42 UTC, merged